### ISSUE TITLE
FAIL tests/cache/test_dbm_backend.py::DBMBackendTest::test_region_expire

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#118]
**Migrated issue, originally created by Ricardo Correia ([wizeman](https://github.com/wizeman))**

I am consistently getting failures when testing dogpile.cache 0.6.4.

Note that this happens on a server that usually also is compiling other programs at the same time, so it may be a bit loaded.

Perhaps it is just a timing issue?

```
tests/cache/test_region.py::ProxyBackendTest::test_argument_proxies PASSED
tests/cache/test_region.py::ProxyBackendTest::test_cachedvalue_passed PASSED
tests/cache/test_region.py::ProxyBackendTest::test_counter_proxies PASSED
tests/cache/test_region.py::ProxyBackendTest::test_instance_proxies PASSED
tests/cache/plugins/test_mako_cache.py::TestMakoPlugin::test_basic PASSED
tests/cache/plugins/test_mako_cache.py::TestMakoPlugin::test_timeout PASSED
tests/util/test_nameregistry.py::NameRegistryTest::test_name_registry PASSED
=========================== short test summary info ============================
FAIL tests/cache/test_dbm_backend.py::DBMBackendTest::test_region_expire
FAIL tests/cache/test_dbm_backend.py::DBMBackendConditionTest::test_region_expire
FAIL tests/cache/test_dbm_backend.py::DBMBackendNoLockTest::test_region_expire

=================================== FAILURES ===================================
______________________ DBMBackendTest.test_region_expire _______________________
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-dogpile.cache-0.6.4.drv-0/dogpile.cache-0.6.4/tests/cache/_fixtures.py", line 276, in test_region_expire
    eq_(reg.get("some key"), "some value 2")
  File "/tmp/nix-build-python3.6-dogpile.cache-0.6.4.drv-0/dogpile.cache-0.6.4/tests/cache/__init__.py", line 11, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: <dogpile.cache.api.NoValue object> != 'some value 2'
__________________ DBMBackendConditionTest.test_region_expire __________________
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-dogpile.cache-0.6.4.drv-0/dogpile.cache-0.6.4/tests/cache/_fixtures.py", line 276, in test_region_expire
    eq_(reg.get("some key"), "some value 2")
  File "/tmp/nix-build-python3.6-dogpile.cache-0.6.4.drv-0/dogpile.cache-0.6.4/tests/cache/__init__.py", line 11, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: <dogpile.cache.api.NoValue object> != 'some value 2'
___________________ DBMBackendNoLockTest.test_region_expire ____________________
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-dogpile.cache-0.6.4.drv-0/dogpile.cache-0.6.4/tests/cache/_fixtures.py", line 276, in test_region_expire
    eq_(reg.get("some key"), "some value 2")
  File "/tmp/nix-build-python3.6-dogpile.cache-0.6.4.drv-0/dogpile.cache-0.6.4/tests/cache/__init__.py", line 11, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: <dogpile.cache.api.NoValue object> != 'some value 2'
=============================== warnings summary ===============================
None
  [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
======== 3 failed, 281 passed, 32 skipped, 1 warnings in 161.18 seconds ========
<3>builder for ‘/nix/store/qmn8gz3ryzzalkn6rya5ad0w3nmbcqh5-python3.6-dogpile.cache-0.6.4.drv’ failed with exit code 1
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**mark thread-intensive tests and disable by default** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2344
