### ISSUE TITLE
AssertionError: Number of slow waiters 15 exceeds expected slow waiters 14.0

### ISSUE THREAD

**Issue by sqlalchemy-bot** [sqlalchemy/dogpile.cache#59]
**Migrated issue, originally created by Jaka Hudoklin ([offlinehacker](https://github.com/offlinehacker))**

I get the following error while running tests:

```
#!python

=====================================================================
FAIL: test_rudimental (tests.core.test_dogpile.ConcurrencyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-dogpile-core-0.4.1.drv-0/dogpile.core-0.4.1/tests/core/test_dogpile.py", line 27, in test_rudimental
    10, exp, crt, nu, ut, dt,
  File "/tmp/nix-build-python2.7-dogpile-core-0.4.1.drv-0/dogpile.core-0.4.1/tests/core/test_dogpile.py", line 323, in _test_multi
    expected_slow_waiters
AssertionError: Number of slow waiters 15 exceeds expected slow waiters 14.0

======================================================================
FAIL: test_get_value_plus_created_registry_safe_cache_quick (tests.core.test_lock.ConcurrencyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python2.7-dogpile-core-0.4.1.drv-0/dogpile.core-0.4.1/tests/core/test_lock.py", line 48, in test_get_value_plus_created_registry_safe_cache_quick
    cache_expire_time='safe'
  File "/tmp/nix-build-python2.7-dogpile-core-0.4.1.drv-0/dogpile.core-0.4.1/tests/core/test_lock.py", line 228, in _test_multi
    expected_slow_waiters
AssertionError: Number of slow waiters 16 exceeds expected slow waiters 14.0

----------------------------------------------------------------------
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**mark thread-intensive tests and disable by default** https://gerrit.sqlalchemy.org/c/sqlalchemy/dogpile.cache/+/2344
